const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '..', 'public');
const outFile = path.join(publicDir, 'sw-assets.js');

const fixed = ['/', '/index.html'];
const includeExt = new Set(['.html', '.css', '.js', '.json', '.svg', '.png', '.ico', '.webp']);
const skip = new Set(['service-worker.js', 'sw-assets.js']);

function walk(dir, base = '') {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = path.join(base, entry.name).replace(/\\/g, '/');
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(abs, rel));
      continue;
    }
    if (skip.has(entry.name)) continue;
    const ext = path.extname(entry.name).toLowerCase();
    if (!includeExt.has(ext)) continue;
    out.push('/' + rel);
  }
  return out;
}

const assets = Array.from(new Set([...fixed, ...walk(publicDir)])).sort();
const content = `/* auto-generated by scripts/generate_sw_assets.js */\nself.__SW_ASSETS = ${JSON.stringify(assets, null, 2)};\n`;
fs.writeFileSync(outFile, content, 'utf8');
console.log(`Generated ${outFile} with ${assets.length} assets`);
