require('dotenv').config();
const mongoose = require('mongoose');

const secondaryUri = String(process.env.MONGO_URI_SECONDARY || '').trim();
const secondaryDb = process.env.MONGO_DB_SECONDARY || undefined;

if (!secondaryUri) {
  console.error('Missing MONGO_URI_SECONDARY in environment');
  process.exit(1);
}

function d(value) {
  return new Date(value);
}

function daysBefore(dateValue, days) {
  const dt = new Date(dateValue);
  dt.setDate(dt.getDate() - days);
  dt.setHours(8, 0, 0, 0);
  return dt;
}

const events = [
  {
    name: 'Big Game Scramble',
    formatType: 'Scramble',
    startDate: d('2026-02-28'),
    endDate: d('2026-02-28'),
    signupOpenAt: d('2026-01-10T08:00:00'),
    signupCloseAt: daysBefore('2026-02-28', 2),
    status: 'open',
    teamSizeMin: 1,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 36,
    maxPlayers: 144,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: false,
    autoWaitlist: true,
    registrationNotes: 'Four-player scramble. Singles are welcome and will be paired.',
    cancellationPolicy: 'Cancel by signup close for full credit.',
  },
  {
    name: 'Shamrock Shamble',
    formatType: 'Shamble',
    startDate: d('2026-03-15'),
    endDate: d('2026-03-15'),
    signupOpenAt: d('2026-01-20T08:00:00'),
    signupCloseAt: daysBefore('2026-03-15', 2),
    status: 'open',
    teamSizeMin: 2,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 36,
    maxPlayers: 144,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Shamble format with net component.',
    cancellationPolicy: 'Cancellation accepted until deadline.',
  },
  {
    name: 'Summer Match Play Registration Deadline',
    formatType: 'Match Play Registration',
    startDate: d('2026-05-01'),
    endDate: d('2026-05-01'),
    signupOpenAt: d('2026-03-01T08:00:00'),
    signupCloseAt: d('2026-05-01T17:00:00'),
    status: 'open',
    teamSizeMin: 1,
    teamSizeMax: 1,
    teamSizeExact: 1,
    maxPlayers: 128,
    allowSingles: true,
    allowSeekingPartner: false,
    allowSeekingTeam: false,
    allowPartialTeamSignup: false,
    allowFullTeamSignup: false,
    allowMemberGuestSignup: false,
    allowCaptainSignup: false,
    allowJoinExistingTeam: false,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Individual registration window for summer match play.',
    cancellationPolicy: 'No cancellation after bracket release.',
  },
  {
    name: 'Cinco de Mayo Cha Cha Cha',
    formatType: 'Cha Cha Cha',
    startDate: d('2026-05-03'),
    endDate: d('2026-05-03'),
    signupOpenAt: d('2026-03-10T08:00:00'),
    signupCloseAt: daysBefore('2026-05-03', 3),
    status: 'open',
    teamSizeMin: 3,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 30,
    maxPlayers: 120,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Four-player Cha Cha Cha. Pairings finalized after signup closes.',
    cancellationPolicy: 'Standard event cancellation policy applies.',
  },
  {
    name: 'Red, White, & Blue',
    formatType: 'Patriotic Team Event',
    startDate: d('2026-07-05'),
    endDate: d('2026-07-05'),
    signupOpenAt: d('2026-05-15T08:00:00'),
    signupCloseAt: daysBefore('2026-07-05', 3),
    status: 'draft',
    teamSizeMin: 2,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 36,
    maxPlayers: 144,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: false,
    autoWaitlist: true,
    registrationNotes: 'Team event with mixed format holes.',
    cancellationPolicy: 'Cancel by signup close to avoid charges.',
  },
  {
    name: 'Member/Member or Member/Guest',
    formatType: 'Member/Member or Member/Guest',
    startDate: d('2026-07-31'),
    endDate: d('2026-08-01'),
    signupOpenAt: d('2026-05-25T08:00:00'),
    signupCloseAt: daysBefore('2026-07-31', 4),
    status: 'draft',
    teamSizeMin: 2,
    teamSizeMax: 2,
    teamSizeExact: 2,
    maxTeams: 64,
    maxPlayers: 128,
    allowSingles: false,
    allowSeekingPartner: true,
    allowSeekingTeam: false,
    allowPartialTeamSignup: false,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: true,
    allowCaptainSignup: true,
    allowJoinExistingTeam: false,
    allowGuests: true,
    memberOnly: false,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Two-player teams. Choose member/member or member/guest division.',
    cancellationPolicy: 'Guest substitutions allowed prior to close date.',
  },
  {
    name: 'Senior Club Championship',
    formatType: 'Club Championship - Senior',
    startDate: d('2026-09-12'),
    endDate: d('2026-09-13'),
    signupOpenAt: d('2026-06-15T08:00:00'),
    signupCloseAt: daysBefore('2026-09-12', 4),
    status: 'draft',
    teamSizeMin: 1,
    teamSizeMax: 1,
    teamSizeExact: 1,
    maxPlayers: 72,
    allowSingles: true,
    allowSeekingPartner: false,
    allowSeekingTeam: false,
    allowPartialTeamSignup: false,
    allowFullTeamSignup: false,
    allowMemberGuestSignup: false,
    allowCaptainSignup: false,
    allowJoinExistingTeam: false,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Senior member individual stroke-play championship.',
    cancellationPolicy: 'No refunds after pairings are posted.',
  },
  {
    name: 'Club Championship',
    formatType: 'Club Championship',
    startDate: d('2026-09-26'),
    endDate: d('2026-09-27'),
    signupOpenAt: d('2026-06-20T08:00:00'),
    signupCloseAt: daysBefore('2026-09-26', 4),
    status: 'draft',
    teamSizeMin: 1,
    teamSizeMax: 1,
    teamSizeExact: 1,
    maxPlayers: 96,
    allowSingles: true,
    allowSeekingPartner: false,
    allowSeekingTeam: false,
    allowPartialTeamSignup: false,
    allowFullTeamSignup: false,
    allowMemberGuestSignup: false,
    allowCaptainSignup: false,
    allowJoinExistingTeam: false,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Individual championship event with flights.',
    cancellationPolicy: 'No cancellation after tee sheet is published.',
  },
  {
    name: 'Super Senior Club Championship',
    formatType: 'Club Championship - Super Senior',
    startDate: d('2026-10-10'),
    endDate: d('2026-10-11'),
    signupOpenAt: d('2026-07-05T08:00:00'),
    signupCloseAt: daysBefore('2026-10-10', 4),
    status: 'draft',
    teamSizeMin: 1,
    teamSizeMax: 1,
    teamSizeExact: 1,
    maxPlayers: 72,
    allowSingles: true,
    allowSeekingPartner: false,
    allowSeekingTeam: false,
    allowPartialTeamSignup: false,
    allowFullTeamSignup: false,
    allowMemberGuestSignup: false,
    allowCaptainSignup: false,
    allowJoinExistingTeam: false,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: true,
    handicapMaxIndex: 36,
    autoWaitlist: true,
    registrationNotes: 'Super senior individual championship.',
    cancellationPolicy: 'No refunds after final draw.',
  },
  {
    name: 'Halloween Devil Ball Challenge',
    formatType: 'Devil Ball Challenge',
    startDate: d('2026-10-25'),
    endDate: d('2026-10-25'),
    signupOpenAt: d('2026-08-01T08:00:00'),
    signupCloseAt: daysBefore('2026-10-25', 3),
    status: 'draft',
    teamSizeMin: 4,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 30,
    maxPlayers: 120,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: false,
    autoWaitlist: true,
    registrationNotes: 'Four-player devil ball challenge with themed pin positions.',
    cancellationPolicy: 'Cancellation cutoff is 72 hours before tee off.',
  },
  {
    name: 'Mad Turkey Scramble',
    formatType: 'Scramble',
    startDate: d('2026-11-07'),
    endDate: d('2026-11-07'),
    signupOpenAt: d('2026-09-01T08:00:00'),
    signupCloseAt: daysBefore('2026-11-07', 3),
    status: 'draft',
    teamSizeMin: 1,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 34,
    maxPlayers: 136,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: false,
    autoWaitlist: true,
    registrationNotes: 'Fall scramble with team prizes.',
    cancellationPolicy: 'Please cancel before close date to avoid a no-show fee.',
  },
  {
    name: 'Reindeer Games',
    formatType: 'Holiday Team Games',
    startDate: d('2026-12-06'),
    endDate: d('2026-12-06'),
    signupOpenAt: d('2026-10-01T08:00:00'),
    signupCloseAt: daysBefore('2026-12-06', 3),
    status: 'draft',
    teamSizeMin: 2,
    teamSizeMax: 4,
    teamSizeExact: 4,
    maxTeams: 30,
    maxPlayers: 120,
    allowSingles: true,
    allowSeekingPartner: true,
    allowSeekingTeam: true,
    allowPartialTeamSignup: true,
    allowFullTeamSignup: true,
    allowMemberGuestSignup: false,
    allowCaptainSignup: true,
    allowJoinExistingTeam: true,
    allowGuests: false,
    memberOnly: true,
    handicapRequired: false,
    autoWaitlist: true,
    registrationNotes: 'Holiday format event with rotating team challenges.',
    cancellationPolicy: 'Standard cancellation policy applies.',
  },
];

async function run() {
  const conn = await mongoose.createConnection(secondaryUri, { dbName: secondaryDb || undefined }).asPromise();
  const BlueRidgeOuting = conn.model('BlueRidgeOuting', require('../models/BlueRidgeOuting').schema);

  let created = 0;
  let updated = 0;

  for (const event of events) {
    const query = { name: event.name, startDate: event.startDate };
    const existing = await BlueRidgeOuting.findOne(query);
    if (existing) {
      await BlueRidgeOuting.updateOne({ _id: existing._id }, { $set: event });
      updated += 1;
    } else {
      await BlueRidgeOuting.create(event);
      created += 1;
    }
  }

  console.log(`Blue Ridge outings seed complete. Created: ${created}, Updated: ${updated}`);
  await conn.close();
}

run().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
